site_name: HotFrameFx User Manual
site_description: User Manual for HotFrameFx, a system tray utility for configuring hot corner and edge actions.
repo_url: https://github.com/kruizer23/hotframefx
edit_uri: edit/main/docs/
nav:
  - Introduction: 'index.md'
  - Getting started: 'getting_started.md'
  - Contributing: 'contributing.md'
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate
    - navigation.top
  palette: 
    - scheme: default
      primary: blue
      accent: red
plugins:
  - search
extra:
  generator: false
copyright: Copyright &copy; 2022 by Frank Voorburg
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences